language: r
cache: packages
warnings_are_errors: false
sudo: false
r_packages:
  - covr
install: travis_wait 30 mvn install

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - Rscript -e 'library(covr); codecov()'
