language: r
cache: packages
script:
  - R CMD build .
  - travis_wait 66 R CMD check BMhyb*tar.gz
warnings_are_errors: false
sudo: false
r_packages:
  - covr

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - Rscript -e 'library(covr); codecov()'
