language: r
cache: packages
script:
  - R CMD build .
  - travis_wait 66 R CMD check BMhyb*tar.gz
warnings_are_errors: false
sudo: false
r_packages:
  - covr

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - Rscript -e 'library(covr); codecov()'
